Resources:
  AlexaOVFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: AlexaSkill
